### ISSUE TITLE
MIMIC3 dataset generation

### ISSUE THREAD

**Issue by KimballCai** [PeterChe1990/GRU-D#2]
Hi Prof.Che,

I am following the processes of the generation for MIMIC_III, and after these preprocesses, I get 136 features for 14716 samples. But in the paper of the GRU-D, there are 99 features for 19714 features. Whether do I miss any process?

Thanks,
Qingpeng

**Comment by PeterChe1990** [comment]
The script now uses the newer version of the MIMIC-III dataset with more tables and a different number of admissions.

**Comment by KimballCai** [comment]
Thanks for your reply.
I am using the MIMIC_III v1.4 which is the latest version released on 2 September 2016. Is it different from the data you used? But the output during the generation processes is the same as the output in these steps.

Thanks,
Qingpeng

**Comment by PeterChe1990** [comment]
The v1.4 is used in the provided notebooks. The results in the paper are from an earlier version of the dataset. The numbers might be slightly different, but all scripts should run smoothly.
