### ISSUE TITLE
Create_model Problem

### ISSUE THREAD

**Issue by nguyendohoangkhoi** [PeterChe1990/GRU-D#5]
![image](https://user-images.githubusercontent.com/37859108/134251638-c7bc8cfd-12cc-47c5-b342-5efa8e842f72.png)
I have an error when I run create model code. I dont understand that (None, 4) should be equal to (None, 4) 
ValueError: The input x and the masking m should have the same input shape, but got (None, 4) and (None, 4).

**Comment by quarkmatter** [comment]
Hi, 

I am also getting the same error. I was able to fix it by modifying line 78 in grud_layers.py: 

`if input_shape[0] != input_shape[1]:` --> `if input_shape[0].as_list() != input_shape[1].as_list():`

**Comment by Yovoss** [comment]
@quarkmatter Hello!,when i import all the function from tensorflow.keras rather than keras, i meet the same question!
but when i take your solution, there is another error:
" AttributeError: 'GRUDCell' object has no attribute 'kernel_z'"
Have you meet this question?
thank you!

**Comment by PeterChe1990** [comment]
Please strictly follow the package dependencies in requirements.txt, as running on later versions has not been tested.
