### ISSUE TITLE
Access the imputed dataset

### ISSUE THREAD

**Issue by noyomer** [PeterChe1990/GRU-D#7]
Hi,
Thanks for this great work! I successfully ran the GRUD on samples (using `run.ipynb`).
I am interested in the imputation output (X' with the imputed values), but it seems that only the prediction performance results are stored. Could you please guide me on how to access the imputed dataset?

Thanks!

**Comment by PeterChe1990** [comment]
Hi moyomer,

As mentioned in the paper, `The proposed method is not explicitly designed for filling in the missing values in the data, and can not be directly used in unsupervised settings without prediction labels.` (https://www.nature.com/articles/s41598-018-24271-9#Sec22)

In the case that the imputed data is indeed needed, you may modify the model and take the output from the last GRU-D layer as the imputation. https://github.com/PeterChe1990/GRU-D/blob/9e1274a1ad67135137f53159eafc92c7278a931a/models.py#L56 (i.e., before the first MLP layer)

**Comment by noyomer** [comment]
Thank you!
